### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by jcarlos1985** [iesoretania/atica-fp#1]
Hola Luis Ramon,

cuando intento ejecutar el comando "gulp" para instalarlo, me lanza el mensaje:
"No gulpfile found".

Los requisitos los cumple el servidor y los pasos anteriores se han ejecutado sin problemas... ¿sabes cómo puedo continuar?

Muchas gracias.

Saludos.

**Comment by lrlopez** [comment]
Hola,

Efectivamente había un error en las instrucciones porque el proyecto ya no usa Gulp.js sino Webpack Encore(https://www.npmjs.com/package/@symfony/webpack-encore). He actualizado las instrucciones. ¡Suerte!
