### ISSUE TITLE
Instalación

### ISSUE THREAD

**Issue by renatolrr** [iesoretania/atica-fp#2]
Estoy intentando la instalacion y no hay manera.
En que distro lo has instalado?
Que me recomiendas?

**Comment by lrlopez** [comment]
Hola Renato. Acabo de revisar la documentación y, efectivamente, hay un paso que está mal. En este proyecto uso [Webpack Encore](https://www.npmjs.com/package/@symfony/webpack-encore) y no Gulp.js para generar los assets. Por tanto las instrucciones no eran correctas. Nosotros lo tenemos todo desplegado en Ubuntu Server 18.04, pero la distro que uses no debería darte problemas si instalas todo lo indicado.

Ya está corregido. ¡Gracias por el aviso!
