### ISSUE TITLE
El usuario no pertenece actualmente a ningún centro educativo.

### ISSUE THREAD

**Issue by renatolrr** [iesoretania/atica-fp#5]
Se ha importado fichero .csv con los docentes del centro, pero solo aparecen como usuarios y no como profesores. Cuando se intenta entrar con el usuario en el programa aparece : El usuario no pertenece actualmente a ningún centro educativo.
Se ha creado un usuario nuevo manualmente, y no existe ningún campo para asociarlo a un centro, 

Muchas gracias.

**Comment by lrlopez** [comment]
La asociación del profesorado al centro de momento sólo puede hacerse mediante la importación. Si se indica que no pertenece a algún centro educativo seguramente sea porque la fecha de cese del docente está en el pasado (la fecha de alta y de cese se importan también, y se deja de pertenecer al centro cuando se cesa). Hasta que se implemente la gestión manual de pertenencias a un centro, la solución más sencilla es poner en blanco la fecha de cese en el fichero .csv

**Comment by lrlopez** [comment]
Cerrado. Resuelto en la versión 5.x.x
